# Generated by Django 2.2.16 on 2022-09-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20220925_2249"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genre_Title",
        ),
    ]
